"""empty message

Revision ID: 394bdcc655c3
Revises: b6d6cffe47d4
Create Date: 2025-04-04 23:13:27.398651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394bdcc655c3'
down_revision = 'b6d6cffe47d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('tipo_estudio',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('RX', 'CT', 'MRI', 'US', 'MAMO', 'PET', name='tipoestudio'),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PROGRAMADA', 'COMPLETADA', 'CANCELADA', 'EN_PROCESO', name='estadocita'),
               existing_nullable=True)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_confirmado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_confirmacion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_expiracion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('historial_medico', sa.Text(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index('ix_pacientes_identificacion', ['identificacion'], unique=True)
        batch_op.create_unique_constraint('uq_pacientes_email', ['email'])
        batch_op.create_unique_constraint('uq_pacientes_identificacion', ['identificacion'])
        batch_op.drop_column('historial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historial', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_pacientes_identificacion', type_='unique')
        batch_op.drop_constraint('uq_pacientes_email', type_='unique')
        batch_op.drop_index('ix_pacientes_identificacion')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('historial_medico')
        batch_op.drop_column('token_expiracion')
        batch_op.drop_column('token_confirmacion')
        batch_op.drop_column('email_confirmado')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('PROGRAMADA', 'COMPLETADA', 'CANCELADA', 'EN_PROCESO', name='estadocita'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('tipo_estudio',
               existing_type=sa.Enum('RX', 'CT', 'MRI', 'US', 'MAMO', 'PET', name='tipoestudio'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###